[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
tschain_sepp = "GPtKmrosprCcr2rUUktPuS5o1ro9RL5222A7BvQ96fB7"

[programs.localnet]
tschain_sepp = "GPtKmrosprCcr2rUUktPuS5o1ro9RL5222A7BvQ96fB7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
